### PR TITLE
WIP: Newbuild using oldwhere

### PR DESCRIPTION
**Pull request by maynardGK**

### CODE REVIEW

**Comment by maynardGK** [comment]
@GillesDuvert I've gotten some very large executables (gdl.exe for 32-bit, GraphicsMagick+WxWidgets=42MB).  This is with older software (code here is vintage Aug 11).

**Comment by maynardGK** [comment]
@slayoo @GillesDuvert 
Something with Appveyor prevents me from building a 32-bit GraphicsMagick directory for use in GDL.
I've done this successfully on my home system by running the appveyor simulation; I get the same configure output but in appveyor it is incomplete and creates an error (see log) that stops the build.
In the alternative case, the appveyor script now skips GM build and uses the 8-bit image package as
distributed by the msys2 repo.  To get this into GDL we can create a build file and submit to github/MSYS and thereby have a usable download.
   In putting this together I see a difference in the configure, that include/freetype2 and include/libxml were not included in the CPPFLAGS of the appveyor run.  Trying that ...

```
This is Powershell console output from running the Graphics Magic Build from home appveyor simulation.

PS C:\Users\greg>         cd c:\projects\gdl\win32libs
PS C:\projects\gdl\win32libs>         $env:CC="C:/mingw-w64/$env:GCC/$env:mname/bin/gcc"
PS C:\projects\gdl\win32libs>         $env:CXX="C:/mingw-w64/$env:GCC/$env:mname/bin/g++"
PS C:\projects\gdl\win32libs>         cd c:/projects/gdl
PS C:\projects\gdl>         $env:GMNAME="GraphicsMagick-1.3.30"
PS C:\projects\gdl>         $env:WXNAME="wxWidgets-3.0.2-17"
PS C:\projects\gdl>         $env:LOCALM32="c:/projects/gdl/mingw/$env:mname"
PS C:\projects\gdl>         $env:PLPLOTDIR="C:\projects\gdl\mingw\plplot-5.13"
PS C:\projects\gdl>         $env:WXROOT="C:\projects\gdl\mingw\$env:WXNAME"
PS C:\projects\gdl>       if ( "x$env:GMNAME" -eq "x")
>>       {
>>       echo "No graphicsmagick build attempted "
>>       }
>>       else
>>       {
>>       echo " $env:GMNAME: 32-bit Quantum GraphicsMagick "
>>       echo " $env:GMNAME "
>>       cmd /c C:\msys64\usr\bin\bash.exe -lc "cd /c/projects/gdl && ./scripts/win32/bld_gm32.msys" 2>$null
>>       }
>>
  32-bit Quantum GraphicsMagick
 GraphicsMagick-1.3.30
 ... etc grphics magick build output ...

 GraphicsMagick-1.3.30 if here
Options used to compile and link:
  CC       = i686-w64-mingw32-gcc
  CFLAGS   = -fopenmp -g -O2 -Wall
  CPPFLAGS = -Ic:/projects/gdl/mingw/mingw32/include -D_DLL -D_MT -I/mingw32/include/freetype2 -I/mingw32/include/libxml
2
  CXX      = i686-w64-mingw32-g++
  CXXFLAGS =
  DEFS     = -DHAVE_CONFIG_H
  LDFLAGS  = -Lc:/projects/gdl/mingw/mingw32/lib -L/mingw32/lib
  LIBS     = -llcms2 -lfreetype -lgs -llzma -lbz2 -lz -lltdl -lgdi32 -lm -lgomp -lpthread

That was tail end of configure.out
libtool: link: ( cd "filters/.libs" && rm -f "analyze.la" && cp -pR "../analyze.la" "analyze.la" )
libtool: link: i686-w64-mingw32-g++ -shared -nostdlib C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../.

  ... 

libtool: link: ( cd "wand/.libs" && rm -f "libGraphicsMagickWand.la" && cp -pR "../libGraphicsMagickWand.la" "libGraphic
sMagickWand.la" )
make[1]: Leaving directory '/c/projects/gdl/win32libs/GraphicsMagick-1.3.30/bldmingw32'
That was tail end of make.out
coders      config      config.status  GraphicsMagick.spec  magick    Makefile    rungm.sh  utilities
common.shi  config.log  filters        libtool              Magick++  PerlMagick  tests     wand
/c/projects/gdl/win32libs/GraphicsMagick-1.3.30/bldmingw32
```

**Comment by GillesDuvert** [comment]
@maynardGK , I'm not sure I understand all things Windows, but in the specific case of 32 bits, it would be indeed so much easier that all the needed packages exist already in some external repo. Rebuilding GDL would be way faster.  It could help to have an old simple plplot such as 5.9.9, as we do not care much about 99% of its content. Ah, also, yes, we are apparently very touchy about the xdr. HIH.

**Comment by maynardGK** [comment]
I think we can host some files under the github account, no? 
There's no reason to downgrade plplot, at version 13 it has a well-developed cmake and the wingdi
device which does superior labelling.  I am building it ok on appveyor in the MSYS2 script .
I've just made a viable script to produce MSYS2-compatible graphicsMagick packages for 32-bits images

```
mingw64/lib/GraphicsMagick-1.3.30/
mingw64/lib/libGraphicsMagick++.dll.a
mingw64/lib/libGraphicsMagick++.la
mingw64/lib/libGraphicsMagick.dll.a
mingw64/lib/libGraphicsMagick.la
mingw64/lib/libGraphicsMagickWand.dll.a
mingw64/lib/libGraphicsMagickWand.la
mingw64/lib/pkgconfig/
mingw64/lib/pkgconfig/GraphicsMagick++.pc
mingw64/lib/pkgconfig/GraphicsMagick.pc
mingw64/lib/pkgconfig/GraphicsMagickWand.pc
mingw64/lib/GraphicsMagick-1.3.30/config/
 ...
mingw64/bin/libGraphicsMagick++-Q32-12.dll
mingw64/bin/libGraphicsMagick-Q32-3.dll
mingw64/bin/libGraphicsMagickWand-Q32-2.dll
```

After these (and bsd-xdr) we have it all on the MSYS2 repository http://repo.msys2.org/mingw/

**Comment by slayoo** [comment]
Perhaps the most maintainable and robust option would be to create a new repo with an Appveyor CI set up just to build the needed libraries and publish an artefact that would then be downloaded from gdl appveyor scripts. This way anyone could also make a PR to the helper-lib-build repo to fix/improve the dependency build?

**Comment by maynardGK** [comment]
We could use the GDL sourceforge account to host, for win32, makepkg directories and the resultant
binaries
```
- plplot, compiled with old_wxwidgets, the drivers/winxxx patches, using only C, CXX code.
- wxWidgets corresponding to that used to make plplot (3.0.2).  
  This is supplied at MSYS2 but its use for GDL requires the wx-config to be tweaked.
- bsd-xdr
- graphicsmagick using 32-bit & library quantum labelling enabled
```
For graphicsmagick the originating directory looks like:
```
-rw-r--r-- 1 greg None   24572 Nov  6 02:08 001-relocate.patch
-rw-r--r-- 1 greg None    3595 Nov  6 02:06 PKGBUILD
```

and after it is built,
```
greg@Homerw7 MSYS /f/github/modified-mingw-w64
$ ls -lat mingw-w64-graphicsmagick-32
total 11269
-rw-r--r-- 1 greg None 2371104 Nov  6 02:21 mingw-w64-i686-graphicsmagick-1.3.30-1-any.pkg.tar.xz
drwxr-xr-x 1 greg None       0 Nov  6 02:21 ./
-rw-r--r-- 1 greg None  220341 Nov  6 02:21 mingw-w64-graphicsmagick-1.3.30-1-i686-package.log
drwxr-xr-x 1 greg None       0 Nov  6 02:20 pkg/
-rw-r--r-- 1 greg None  420812 Nov  6 02:20 mingw-w64-graphicsmagick-1.3.30-1-i686-build.log
drwxr-xr-x 1 greg None       0 Nov  6 02:16 src/
-rw-r--r-- 1 greg None    1958 Nov  6 02:16 mingw-w64-graphicsmagick-1.3.30-1-i686-prepare.log
-rw-r--r-- 1 greg None 2323376 Nov  6 02:16 mingw-w64-x86_64-graphicsmagick-1.3.30-1-any.pkg.tar.xz
-rw-r--r-- 1 greg None  222329 Nov  6 02:15 mingw-w64-graphicsmagick-1.3.30-1-x86_64-package.log
-rw-r--r-- 1 greg None  423952 Nov  6 02:15 mingw-w64-graphicsmagick-1.3.30-1-x86_64-build.log
-rw-r--r-- 1 greg None    1958 Nov  6 02:11 mingw-w64-graphicsmagick-1.3.30-1-x86_64-prepare.log
-rw-r--r-- 1 greg None     227 Nov  6 02:09 mingw-w64-graphicsmagick-1.3.30-1-x86_64-prepare.log.1
-rw-r--r-- 1 greg None   24572 Nov  6 02:08 001-relocate.patch
-rw-r--r-- 1 greg None    3595 Nov  6 02:06 PKGBUILD
-rw-r--r-- 1 greg None 5496116 Nov  6 01:58 GraphicsMagick-1.3.30.tar.xz
drwxr-xr-x 1 greg None       0 Nov  5 23:59 ../
```

So it can all get cleaned up except for the tar.xz files, which can get a name change. 
these files unpack to mingw32/ and mingw64/ directory trees, respectively, and they are also compatible with the MSYS2 pacman usage.

```
greg@Homerw7 MSYS /f/github/modified-mingw-w64/mingw-w64-graphicsmagick-32
$ tar tf ./mingw-w64-i686-graphicsmagick-1.3.30-1-any.pkg.tar.xz | head
.PKGINFO
.BUILDINFO
.MTREE
mingw32/
mingw32/bin/
mingw32/include/
mingw32/lib/
mingw32/share/
mingw32/share/doc/
mingw32/share/GraphicsMagick-1.3.30/

```

**Comment by slayoo** [comment]
SF stability is already causing us trouble with Appveyor build IIUC, hence I would advice against relying on SF + automating re-builds of these dependencies would be a great step towards making these builds maintainable by other developers.

**Pull request closed without merging**
