### PR TITLE
temporarily disabling travis builds for this branch

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
@maynardGK please do accept this one - currently every change you test on Appveyor triggers 10 builds (good 5 hours of CPU time) on Travis. Besides avoiding to be blacklisted (which does happen e.g. for Apple builds), this also causes other GDL travis builds to be queued. Thanks

**Comment by maynardGK** [comment]
I would accept it if I knew how! the last one didn't take.  I've been closing the PR and later opening with a change, but I just saw the appveyor was working on the previous, and the current, with the new commands.
OK I confirm my local git has travis.yml.off

**Comment by slayoo** [comment]
thanks!

**Comment by maynardGK** [comment]
Ok but now I need your help to restart it .  There is a conflict and write access is required.

**Comment by slayoo** [comment]
I'll be driving a few hours now. Isn't the conflict unrelated? (prob. caused by today's merge of Sylvain's PR with a change to appveyor.yml). write permissions should not be an issue here

**Comment by maynardGK** [comment]
I can't write regarding this file, is the problem.  I could pull your commit to my local, but now the PR has a merge conflict.  I'm ok with a wait, I'm pretty sure this last thing is it - from transitive library dependencies: gettext code was needed (libintl-8.dll) but the download didn't provide it.

**Pull request merged**
